import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { copyFileSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = fileURLToPath(new URL("../", import.meta.url));
execFileSync(
  "cargo",
  [
    "build",
    "--locked",
    "--profile",
    "web",
    "--target",
    "wasm32-unknown-unknown",
    "-p",
    "cozy-go-web",
  ],
  { cwd: root, stdio: "inherit" },
);
const bytes = readFileSync(
  path.join(root, "target/wasm32-unknown-unknown/web/cozy_go_web.wasm"),
);
const wasmSha256 = createHash("sha256").update(bytes).digest("hex");
const sources = [
  "Cargo.toml",
  "Cargo.lock",
  "LICENSE",
  "NOTICE",
  "src/lib.rs",
  "src/bitset.rs",
  "src/go.rs",
  "src/gomoku.rs",
  "bindings/web/Cargo.toml",
  "bindings/web/src/lib.rs",
  "bindings/web/pkg/index.ts",
  "rust-toolchain.toml",
  "scripts/build-web.mjs",
].sort();
const hash = createHash("sha256");
for (const source of sources) {
  hash.update(source + "\0");
  hash.update(readFileSync(path.join(root, source)));
  hash.update("\0");
}
const manifest = {
  abiVersion: 1,
  rustc: execFileSync("rustc", ["--version"], {
    cwd: root,
    encoding: "utf8",
  }).trim(),
  sourceSha256: hash.digest("hex"),
  wasmSha256,
  wasmBytes: bytes.length,
};
const output = path.join(root, "bindings/web/pkg");
for (const name of ["LICENSE", "NOTICE"])
  copyFileSync(path.join(root, name), path.join(output, name));
writeFileSync(
  path.join(output, "wasm-data.ts"),
  `// Generated by scripts/build-web.mjs; WASM SHA-256: ${wasmSha256}\nexport const WASM_BASE64 = ${JSON.stringify(bytes.toString("base64"))};\n`,
);
writeFileSync(
  path.join(output, "manifest.json"),
  JSON.stringify(manifest, null, 2) + "\n",
);
console.log(`cozy-go web: ${bytes.length} bytes, ${wasmSha256}`);
